/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.smartprice.views;

import ar.com.smartprice.dtos.UserDto;
import java.awt.BorderLayout;


/**
 *
 * @author ze
 */
public class MainWindowFrame extends javax.swing.JFrame {
    
    public LoginPanel loginPanel;
    
    
    //userPanel = new javax.swing.JPanel();
    //public SignInButtonPanel signInButton;
    public UserSignInPanel userSignInPanel;
    public LogoPanel logoPanel;
    public SearcherPanel searcher;
    


    /**
     * Creates new form FrameVentPpal
     */
    public MainWindowFrame() {
        initComponents();
        
        loginPanel = new LoginPanel();
        loginPanel.setSize(220, 364);
        loginPanel.setLocation(2, 5);
        
        userPanel.removeAll();
        userPanel.add(loginPanel, BorderLayout.CENTER);
        userPanel.revalidate();
        userPanel.repaint();
        
        this.userSignInPanel = new UserSignInPanel();
        
        /*
        this.signInButton = new SignInButtonPanel();
        signInButton.setSize(220, 100);
        signInButton.setLocation(2, 5);
        
        mainPanel2.removeAll();
        mainPanel2.add(signInButton, BorderLayout.CENTER);
        mainPanel2.revalidate();
        mainPanel2.repaint();
        */
        
        this.logoPanel = new LogoPanel();
        logoPanel.setSize(400, 105);
        logoPanel.setLocation(2, 5);
        
        mainPanel3.removeAll();
        mainPanel3.add(logoPanel, BorderLayout.CENTER);
        mainPanel3.revalidate();
        mainPanel3.repaint();
        
        this.searcher = new SearcherPanel();
        searcher.setSize(520, 380);
        searcher.setLocation(2, 5);
        
        mainPanel4.removeAll();
        mainPanel4.add(searcher, BorderLayout.CENTER);
        mainPanel4.revalidate();
        mainPanel4.repaint();
        
    }
    
    public void createAndShowUserSignPanel(){
        //this.userSignInPanel = new UserSignInPanel();
        userSignInPanel.setSize(220, 600);
        userSignInPanel.setLocation(0, 5);
        
        userPanel.removeAll();
        userPanel.add(userSignInPanel, BorderLayout.CENTER);
        userPanel.revalidate();
        userPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        mainPanel3 = new javax.swing.JPanel();
        mainPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartPrice\n");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        userPanel.setPreferredSize(new java.awt.Dimension(220, 364));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel3.setPreferredSize(new java.awt.Dimension(400, 105));

        javax.swing.GroupLayout mainPanel3Layout = new javax.swing.GroupLayout(mainPanel3);
        mainPanel3.setLayout(mainPanel3Layout);
        mainPanel3Layout.setHorizontalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        mainPanel3Layout.setVerticalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanel4Layout = new javax.swing.GroupLayout(mainPanel4);
        mainPanel4.setLayout(mainPanel4Layout);
        mainPanel4Layout.setHorizontalGroup(
            mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanel4Layout.setVerticalGroup(
            mainPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(mainPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel3;
    private javax.swing.JPanel mainPanel4;
    public javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
