/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.smartprice.views;

import ar.com.smartprice.dtos.PrecioDto;
import ar.com.smartprice.models.services.GmapService;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Andres
 */
public class ProductDetails extends javax.swing.JPanel {

    /**
     * Creates new form ProductDetails
     */
    public ProductDetails() {
        initComponents();
    }

    public void setData(PrecioDto p) {
        //TODO ordenar por aparicion
        this.labelProdName.setText(p.getProducto().getNombre());
        this.labelProdDesc.setText(p.getProducto().getDescripcion());
        this.labelProdPrice.setText(String.valueOf(p.getPrecio()));

        //TODO revisar si es una oferta o si es la compra minima
        if (p.getCompraMinima() > 1) {
            this.labelProdOffer.setText(String.valueOf(p.getCompraMinima()));
            this.labelProdOfferDescription.setText(p.getDescripcion());
            this.labelProdOfferPrice.setText(String.valueOf(p.getPrecio() * p.getCompraMinima()));
        }
        else{
            this.remove(this.labelProdOffer);
            this.remove(this.labelProdOfferDescription);
            this.remove(this.labelProdOfferPrice);
        }
        
        //TODO Falta agregar Calificacion
        this.labelOferentName.setText(String.valueOf(p.getOferente().getBusinessName()));
        this.labelAdress.setText(p.getOferente().getDireccion());
        if(p.getGmap().getDistanceWalk()!=0){
            this.labelDistance.setText(String.valueOf(p.getGmap().getDistanceWalk()) + " metros");
        }
        

        Image image = GmapService.getImage(p.getGmap().getSimpleImage());
        this.labelGoogleImage.setText(null);
        this.labelGoogleImage.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProdName = new javax.swing.JLabel();
        labelProdDesc = new javax.swing.JLabel();
        labelOferentName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelProdPrice = new javax.swing.JLabel();
        labelProdOffer = new javax.swing.JLabel();
        labelAdress = new javax.swing.JLabel();
        labelDistance = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelGoogleImage = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelProdOfferDescription = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelProdOfferPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 241, 245));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 171, 170)));

        labelProdName.setForeground(new java.awt.Color(73, 79, 94));
        labelProdName.setText("Nombre del producto");
        labelProdName.setName("labelNameProduct"); // NOI18N

        labelProdDesc.setForeground(new java.awt.Color(73, 79, 94));
        labelProdDesc.setText("Descripcion del producto");
        labelProdDesc.setName("labelDescription"); // NOI18N

        labelOferentName.setForeground(new java.awt.Color(73, 79, 94));
        labelOferentName.setText("Nombre del Oferente");
        labelOferentName.setName("labelOfName"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(73, 79, 94));

        jLabel4.setBackground(new java.awt.Color(236, 241, 245));
        jLabel4.setForeground(new java.awt.Color(236, 241, 245));
        jLabel4.setText("UBICACION Y DETALLES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setForeground(new java.awt.Color(73, 79, 94));
        jLabel5.setText("NOMBRE:");

        jLabel6.setForeground(new java.awt.Color(73, 79, 94));
        jLabel6.setText("DESCRIPCION:");

        jLabel7.setForeground(new java.awt.Color(73, 79, 94));
        jLabel7.setText("PRECIO REGULAR:");

        jLabel8.setForeground(new java.awt.Color(73, 79, 94));
        jLabel8.setText("OFERTA:");

        jLabel9.setForeground(new java.awt.Color(73, 79, 94));
        jLabel9.setText("CALIFICACION:");

        jLabel10.setForeground(new java.awt.Color(73, 79, 94));
        jLabel10.setText("OFERENTE:");

        jLabel11.setForeground(new java.awt.Color(73, 79, 94));
        jLabel11.setText("DIRECCION:");

        jLabel12.setForeground(new java.awt.Color(73, 79, 94));
        jLabel12.setText("DISTANCIA:");

        labelProdPrice.setForeground(new java.awt.Color(73, 79, 94));
        labelProdPrice.setText("Precio");
        labelProdPrice.setName("labelPrice"); // NOI18N

        labelProdOffer.setForeground(new java.awt.Color(73, 79, 94));
        labelProdOffer.setText("No dispone");
        labelProdOffer.setName("labelOferta"); // NOI18N

        labelAdress.setForeground(new java.awt.Color(73, 79, 94));
        labelAdress.setText("Direccion");
        labelAdress.setName("labelAdress"); // NOI18N

        labelDistance.setForeground(new java.awt.Color(73, 79, 94));
        labelDistance.setText("No disponible");
        labelDistance.setName("labelDistance"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(73, 79, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 171, 170)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 241, 245));
        jLabel1.setText("NO IMAGE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(73, 79, 94));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 171, 170), 1, true));

        labelGoogleImage.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelGoogleImage.setForeground(new java.awt.Color(236, 241, 245));
        labelGoogleImage.setText("GOOGLE MAPS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelGoogleImage)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(labelGoogleImage)
                .addGap(44, 44, 44))
        );

        jLabel13.setForeground(new java.awt.Color(73, 79, 94));
        jLabel13.setText("DESC. OFERTA:");

        labelProdOfferDescription.setForeground(new java.awt.Color(73, 79, 94));
        labelProdOfferDescription.setText("No dispone");
        labelProdOfferDescription.setName("labelOferta"); // NOI18N

        jLabel14.setForeground(new java.awt.Color(73, 79, 94));
        jLabel14.setText("PRECIO OFERTA:");

        labelProdOfferPrice.setForeground(new java.awt.Color(73, 79, 94));
        labelProdOfferPrice.setText("No dispone");
        labelProdOfferPrice.setName("labelOferta"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelProdDesc)
                                    .addComponent(labelProdName)))
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDistance)
                                    .addComponent(labelAdress)
                                    .addComponent(labelOferentName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelProdOfferDescription)
                                    .addComponent(labelProdPrice)
                                    .addComponent(labelProdOffer)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(labelProdOfferPrice)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProdName)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProdDesc)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labelProdPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(labelProdOffer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(labelProdOfferDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(labelProdOfferPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelOferentName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(labelAdress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(labelDistance))))
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAdress;
    private javax.swing.JLabel labelDistance;
    private javax.swing.JLabel labelGoogleImage;
    private javax.swing.JLabel labelOferentName;
    private javax.swing.JLabel labelProdDesc;
    private javax.swing.JLabel labelProdName;
    private javax.swing.JLabel labelProdOffer;
    private javax.swing.JLabel labelProdOfferDescription;
    private javax.swing.JLabel labelProdOfferPrice;
    private javax.swing.JLabel labelProdPrice;
    // End of variables declaration//GEN-END:variables
}
