/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.smartprice.views;

import ar.com.smartprice.dtos.UserDto;
import ar.com.smartprice.models.services.GmapService;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author Andres
 */
public class ProfilePanel extends javax.swing.JPanel implements FocusListener {

    private String direccionValidada = "";

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
        setLocationAndSize();
        this.txtAddress.addFocusListener(this);

    }

    private void setLocationAndSize() {
        setSize(520, 380);
        setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblRePassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        btnDeleteAccount = new javax.swing.JButton();
        lblCUIT = new javax.swing.JLabel();
        btnUpdateProfile = new javax.swing.JButton();
        lblBusinessName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        txtCUIT = new javax.swing.JTextField();
        txtBusinessName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 241, 245));

        lblEmail.setForeground(new java.awt.Color(75, 82, 97));
        lblEmail.setText("E-Mail:");

        lblPassword.setForeground(new java.awt.Color(75, 82, 97));
        lblPassword.setText("Contraseña:");

        lblRePassword.setForeground(new java.awt.Color(75, 82, 97));
        lblRePassword.setText("Repetir contraseña:");

        lblName.setForeground(new java.awt.Color(75, 82, 97));
        lblName.setText("Nombre:");

        lblAddress.setForeground(new java.awt.Color(75, 82, 97));
        lblAddress.setText("Direccion:");

        btnDeleteAccount.setBackground(new java.awt.Color(0, 171, 170));
        btnDeleteAccount.setForeground(new java.awt.Color(236, 241, 245));
        btnDeleteAccount.setText("Borrar Cuenta");
        btnDeleteAccount.setBorder(null);
        btnDeleteAccount.setFocusPainted(false);

        lblCUIT.setForeground(new java.awt.Color(75, 82, 97));
        lblCUIT.setText("CUIT:");

        btnUpdateProfile.setBackground(new java.awt.Color(0, 171, 170));
        btnUpdateProfile.setForeground(new java.awt.Color(236, 241, 245));
        btnUpdateProfile.setText("Actualizar Datos");
        btnUpdateProfile.setBorder(null);
        btnUpdateProfile.setFocusPainted(false);

        lblBusinessName.setForeground(new java.awt.Color(75, 82, 97));
        lblBusinessName.setText("Razon social:");

        txtName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 82, 97)));

        txtAddress.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 82, 97)));

        txtPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 82, 97)));

        txtRePassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtRePassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 82, 97)));

        txtCUIT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCUIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 82, 97)));

        txtBusinessName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBusinessName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 82, 97)));

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 82, 97)));
        txtEmail.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(75, 82, 97));

        lblTitle.setForeground(new java.awt.Color(236, 241, 245));
        lblTitle.setText("Perfil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblName)
                                .addComponent(lblAddress)
                                .addComponent(lblCUIT)
                                .addComponent(lblBusinessName))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCUIT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtName)
                                .addComponent(txtBusinessName)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPassword)
                                .addComponent(lblEmail))
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPassword)
                                .addComponent(txtEmail)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblRePassword)
                            .addGap(18, 18, 18)
                            .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRePassword)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCUIT)
                    .addComponent(txtCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusinessName)
                    .addComponent(txtBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteAccount;
    public javax.swing.JButton btnUpdateProfile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBusinessName;
    private javax.swing.JLabel lblCUIT;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRePassword;
    private javax.swing.JLabel lblTitle;
    public javax.swing.JTextField txtAddress;
    public javax.swing.JTextField txtBusinessName;
    public javax.swing.JTextField txtCUIT;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtName;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JPasswordField txtRePassword;
    // End of variables declaration//GEN-END:variables

    void setUser(UserDto user) {
        switch (user.getUserType()) {

            case 2:
                //muestra los campos del usuario
                System.out.println("Mostrar campos y cargar datos de Usuario");
                this.lblName.setVisible(false);
                this.txtName.setVisible(false);

                this.lblAddress.setVisible(false);
                this.txtAddress.setVisible(false);

                this.lblCUIT.setVisible(false);
                this.txtCUIT.setVisible(false);

                this.lblBusinessName.setVisible(false);
                this.txtBusinessName.setVisible(false);
                break;
            case 3:
                //muestra los campos del Oferente
                System.out.println("Mostrar campos y cargar datos de Oferente");
                this.lblName.setVisible(true);
                this.txtName.setVisible(true);

                this.lblAddress.setVisible(true);
                this.txtAddress.setVisible(true);

                this.lblCUIT.setVisible(true);
                this.txtCUIT.setVisible(true);

                this.lblBusinessName.setVisible(true);
                this.txtBusinessName.setVisible(true);

                this.txtEmail.setText(user.getEmail());
                this.txtName.setText(user.getName());
                this.txtAddress.setText(user.getDireccion());
                this.txtCUIT.setText(user.getCuit());
                this.txtBusinessName.setText(user.getBusinessName());
                break;
        }
    }

    @Override
    public void focusGained(FocusEvent fe) {
        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void focusLost(FocusEvent fe) {
        if (fe.getSource() == this.txtAddress
                && !direccionValidada.equalsIgnoreCase(txtAddress.getText())) {//Evita revalidar si no hay cambios
            this.validarDireccion();
        }
    }

    private void validarDireccion() {
        direccionValidada = GmapService.validateAddress(txtAddress.getText());
        txtAddress.setText(direccionValidada);
        txtAddress.setCaretPosition(0);
        if (direccionValidada.equalsIgnoreCase("Direccion Invalida")){
            btnUpdateProfile.setEnabled(false);
        }
        else{
            btnUpdateProfile.setEnabled(true);
        }

    }

    public void clearFields() {
        this.txtEmail.setText(null);
        this.txtPassword.setText(null);
        this.txtRePassword.setText(null);
        this.txtName.setText(null);
        this.txtAddress.setText(null);
        this.txtCUIT.setText(null);
        this.txtBusinessName.setText(null);
    }
}
